import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/page";
import Footer from "./components/Footer/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-Br">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
